Repository fga-eps-mds/2019.1-ADA, pull requests merged in 2019-04, with the labels that each got.

#64 #63 Create Sprint2 planning
  _sidebar.md
  docs/sprints/planejamento_sprint2.md
Labels: Documentação, EPS, Scrum Master

#67 #15 Create architecture document.
  _sidebar.md
  docs/img/architecture/Arquitetura_1.0.png
  docs/project/architecture_doc.md
  index.html
Labels: Arquitetura

#66 65 folha de estilo
  _sidebar.md
  docs/opening_and_specification/eap.md
  docs/style_guide/style_guide.md
Labels: DevOps, Documentação

#70 #29 Adição de página sobre Identidade Visual
  _sidebar.md
  docs/img/visual_identity/color_palette.png
  docs/opening_and_specification/visual_identity.md
Labels: Documentação

#69 #68 Criar questionário
  _sidebar.md
  docs/img/questionnaire/ci.png
  docs/img/questionnaire/communication.png
  docs/img/questionnaire/deploy.png
  docs/img/questionnaire/versioning.png
  docs/requirements_engineering/questionnaire.md
Labels: Documentação

#71 #61 Criar Roadmap do Produto
  _sidebar.md
  docs/img/roadmaps/product_roadmap_v1.jpg
  docs/img/roadmaps/roadmap_sprint_v1.jpg
  docs/opening_and_specification/canvas.md
  docs/opening_and_specification/eap.md
  docs/opening_and_specification/termo_de_abertura_do_projeto.md
  docs/roadmaps/product_roadmap.md
Labels: Documentação, EPS, Product Owner

#73 #29 Adição de Histórico de Revisão de Identidade Visual
  docs/opening_and_specification/visual_identity.md
Labels: Documentação

#78 #56 Eu, como desenvolvedor, quero conectar o Rasa ao Telegram para que a Ada possa conversar com o usuário.
  .gitignore
  ada/Makefile
  ada/actions/.gitkeep
  ada/credentials.yml
  ada/data/intents/nlu.md
  ada/data/stories/stories.md
  ada/domain.yml
  ada/endpoints.yml
  ada/instructions.md
  ada/nlu_config.yml
  ada/policy_config.yml
  ada/run-telegram.py
  ada/train.py
  docker-compose-dev.yml
  docker/ada.Dockerfile
  manage.py
  requirements.txt
Labels: DevOps, MDS

#76 #72 Criação e priorização de backlog do produto
  _sidebar.md
  docs/project/backlog.md
Labels: Documentação, EPS, Product Owner

#79 #58 Planejamento de Riscos
  _sidebar.md
  docs/img/risks/EAR.jpg
  docs/project/risk_management_plan.md
Labels: Documentação, EPS, Scrum Master

#74 #29 Modificações nas páginas Identidade Visual e Personalidade do Bot
  docs/opening_and_specification/bot_personality.md
  docs/opening_and_specification/visual_identity.md
Labels: Documentação

#82 #59 Evolução Gitflow
  docs/opening_and_specification/canvas.md
  docs/project/gitflow.md
Labels: DevOps, Documentação

#83 #62 Add roles roadmap
  _sidebar.md
  docs/img/roadmaps/roles_roadmap_v1.jpg
  docs/roadmaps/roles_roadmap.md
Labels: Arquitetura, DevOps, Documentação, EPS, Product Owner, Scrum Master

#96 24 escopo
  _sidebar.md
  docs/img/scope/escopo.png
  docs/opening_and_specification/scope.md
  docs/sprints/resultados_sprint2.md
  index.html
Labels: Documentação

#95 #84 Criar o Documento de Planejamento da Sprint 3
  _sidebar.md
  docs/sprints/planejamento_sprint3.md
Labels: Documentação, EPS, Scrum Master

#100 #99 Hotfix atualiza docker
  .gitignore
  ada/actions/actions.py
  docker-compose-dev.yml
  docker/actions.Dockerfile
  docker/actions.requirements.txt
  docker/ada.Dockerfile
  docker/ada.requirements.txt
Labels: DevOps, EPS

#102 Hotfix docker
  docker-compose-dev.yml
  docker/actions.Dockerfile
  docker/actions.requirements.txt
  docker/ada.Dockerfile
  manage.py
Labels: DevOps, EPS

#103 #94 cria ambiente teste
  .gitlab-ci.yml
  ada/actions/actions.py
  ada/run-telegram.py
  ada/train.py
  docker/ada.requirements.txt
Labels: DevOps, EPS

#105 91 identidade visual
  _coverpage.md
  docs/assets/css/home.css
  docs/assets/gifs/BackGround.gif
  docs/assets/img/logo/Ada.png
  docs/assets/img/logo/Ada_logo.png
  docs/assets/img/logo/Ada_logo_horizontal.png
  docs/assets/img/logo/Ada_logo_vertical.png
  docs/assets/img/logo/logoAda.png
  docs/product/visual_identity.md
  docs/project/architecture_doc.md
  index.html
Labels: Product

#104 #87 - Eu, como usuário, desejo ser cumprimentado pela Ada para iniciar uma conversa.
  ada/actions/action_who_is_ada.py
  ada/data/intents/nlu.md
  ada/data/intents/who_is_ada.md
  ada/data/stories/stories.md
  ada/data/stories/who_is_ada_storie.md
  ada/domain.yml
  ada/nlu_config.yml
  docker-compose-dev.yml
  docker/actions.Dockerfile
  docker/actions.requirements.txt
  docker/ada.Dockerfile
  docker/ada.requirements.txt
Labels: MDS, enhancement

#119 #107 Sprint3 Results
  _sidebar.md
  docs/assets/img/sprints/sprint3/burndown_de_riscos_sprint3.png
  docs/assets/img/sprints/sprint3/burndown_sprint3.ong
  docs/assets/img/sprints/sprint3/burndown_sprint3.png
  docs/assets/img/sprints/sprint3/quadro_de_conhecimentos_sprint3.png
  docs/assets/img/sprints/sprint3/tvi_sprint3.png
  docs/assets/img/sprints/sprint3/velocity_sprint3.png
  docs/assets/img/sprints/sprint3/work_capacity_sprint3.png
  docs/sprints/sprint3/resultados_sprint3.md
Labels: Scrum Master

#120 #108 Sprint4 Planing
  _sidebar.md
  docs/sprints/sprint4/planejamento_sprint4.md
Labels: Scrum Master

#122 #112 Refatorar Fluxo de Conversa
  ada/actions/action_who_is_ada.py
  ada/data/intents/compliments.md
  ada/data/intents/general.md
  ada/data/intents/nlu.md
  ada/data/intents/random.md
  ada/data/intents/who_is_ada.md
  ada/data/stories/actions.md
  ada/data/stories/stories.md
  ada/data/stories/who_is_ada_storie.md
  ada/domain.yml
  ada/run-telegram.py
  docker-compose-dev.yml
Labels: MDS

#121 #115 Refatorar formatação de documentos no GitHub Pages
  README.md
  _sidebar.md
  docs/assets/img/sprints/sprint1/quadro_de_conhecimentos_sprint1.png
  docs/assets/img/sprints/sprint2/quadro_de_conhecimentos_sprint2.png
  docs/policies/branches.md
  docs/policies/commits.md
  docs/policies/issues.md
  docs/policies/policies.md
  docs/policies/pull_request.md
  docs/product/bot_personality.md
  docs/product/canvas.md
  docs/product/eap.md
  docs/product/questionnaire.md
  docs/product/rich_picture.md
  docs/product/tap.md
  docs/product/visual_identity.md
  docs/project/backlog.md
  docs/project/communication_plan.md
  docs/project/gitflow.md
  docs/project/risk_management_plan.md
  docs/project/style_guide.md
  docs/roadmaps/product_roadmap.md
  docs/roadmaps/roles_roadmap.md
  docs/sprints/sprint0/planejamento_sprint0.md
  docs/sprints/sprint1/planejamento_sprint1.md
Labels: Documentação

#123 #112 - Refatorar Fluxo De Conversa
  ada/data/intents/general.md
  ada/data/intents/nlu.md
  ada/data/intents/random.md
  ada/data/stories/stories.md
  ada/domain.yml
  docker/actions.requirements.txt
Labels: MDS

#124 #111 Matriz de Avaliação de Valor
  _sidebar.md
  docs/assets/img/product/blue_ocean_strategy/errc_grid_v0_1.png
  docs/assets/img/product/blue_ocean_strategy/errc_grid_v1.png
  docs/assets/img/product/blue_ocean_strategy/strategy_canvas_v0_1.png
  docs/assets/img/product/blue_ocean_strategy/strategy_canvas_v1.png
  docs/product/blue_ocean_strategy.md
Labels: Documentação, EPS, Product Owner

#126 #116 Fazer Plano de Medição
  _sidebar.md
  docs/project/measuring_plane.md
Labels: Documentação, EPS, Scrum Master

#125 #111 Referências do Oceano Azul
  docs/product/blue_ocean_strategy.md
Labels: Documentação, EPS, Product Owner

#128 #113 pipeline machine learning
  README.md
  _sidebar.md
  docs/project/machine_learning_pipeline.md
Labels: Arquitetura, Documentação, EPS

#127 #109 Eu, como usuário, desejo saber o estágio da build para saber o andamento do processo.
  ada/actions/action_build_stage.py
  ada/data/intents/build_stage.md
  ada/data/intents/nlu.md
  ada/data/stories/build_stage_storie.md
  ada/data/stories/stories.md
  ada/domain.yml
  ada/instructions.md
  docker-compose-dev.yml
Labels: MDS, enhancement

#140 #129 Criar Documento de Resultados da Sprint 4
  _sidebar.md
  docs/assets/img/sprints/sprint4/burndown_de_riscos_sprint4.png
  docs/assets/img/sprints/sprint4/burndown_sprint4.png
  docs/assets/img/sprints/sprint4/quadro_de_conhecimentos_sprint4.png
  docs/assets/img/sprints/sprint4/tvi_sprint4.png
  docs/assets/img/sprints/sprint4/velocity_sprint4.png
  docs/assets/img/sprints/sprint4/work_capacity_day_sprint4.png
  docs/assets/img/sprints/sprint4/work_capacity_sprint4.png
  docs/sprints/sprint4/resultados_sprint4.md
Labels: Documentação, Scrum Master

#141 #130 Criar Documento de Planejamento da Sprint 5
  _sidebar.md
  docs/sprints/sprint5/planejamento_sprint5.md
Labels: Documentação, Scrum Master

#144 Refatoração do Readme
  .gitignore
  CONTRIBUTING.md
  README.md
Labels: Documentação, MDS, Melhoria

#145 #138 Update contributing guidelines in accordance with read me file
  CONTRIBUTING.md
Labels: Documentação

#142 #88 US26 AdaGitLab
  ada/actions/actions.py
  ada/actions/get_pipeline.py
  ada/actions/set_repositorie.py
  ada/actions/set_user.py
  ada/data/intents/actions.md
  ada/data/stories/stories.md
  ada/domain.yml
  docker-compose-dev.yml
  docker/actions.Dockerfile
  docker/actions.requirements.txt
Labels: MDS

#146 Remove coverage badge from another service
  README.md
Labels: Documentação, Melhoria

#147 #118 deploy
  .gitlab-ci.yml
  docker-compose-dev.yml
  docker/actions.Dockerfile
Labels: DevOps, EPS

#148 Envio do código para branch master
  .gitignore
  .gitlab-ci.yml
  CONTRIBUTING.md
  README.md
  ada/Makefile
  ada/actions/.gitkeep
  ada/actions/action_build_stage.py
  ada/actions/get_pipeline.py
  ada/actions/set_repositorie.py
  ada/actions/set_user.py
  ada/credentials.yml
  ada/data/intents/actions.md
  ada/data/intents/build_stage.md
  ada/data/intents/compliments.md
  ada/data/intents/general.md
  ada/data/intents/nlu.md
  ada/data/intents/random.md
  ada/data/stories/build_stage_storie.md
  ada/data/stories/stories.md
  ada/domain.yml
  ada/endpoints.yml
  ada/instructions.md
  ada/nlu_config.yml
  ada/policy_config.yml
  ada/run-telegram.py
  ada/train.py
  docker-compose-dev.yml
  docker/actions.Dockerfile
  docker/actions.requirements.txt
  docker/ada.Dockerfile
  docker/ada.requirements.txt
Labels: EPS

#151 Atualização do documento de gitflow
  docs/assets/img/project/gitflow/gitflow.jpg
  docs/project/gitflow.md
Labels: DevOps, EPS

#150 #136 Fix some messages
  ada/data/intents/nlu.md
  ada/domain.yml
Labels: MDS, Melhoria, Product

#160 #152 Criar Documento de Resultados da Sprint 5
  _sidebar.md
  docs/assets/img/sprints/sprint4/work_capacity_sprint4.png
  docs/assets/img/sprints/sprint5/burndown_de_riscos_sprint5.png
  docs/assets/img/sprints/sprint5/burndown_sprint5.png
  docs/assets/img/sprints/sprint5/quadro_de_conhecimentos_sprint5.png
  docs/assets/img/sprints/sprint5/tvi_sprint5.png
  docs/assets/img/sprints/sprint5/velocity_sprint5.png
  docs/sprints/sprint5/resultados_sprint5.md
Labels: Documentação, Scrum Master

#161 #153 Criar Documento de Planejamento da Sprint 6
  _sidebar.md
  docs/sprints/sprint6/planejamento_sprint6.md
Labels: Documentação, Scrum Master

#164 #133 teste em uso
  _sidebar.md
  docs/product/in_use_test.md
Labels: EPS, Product, Product Owner

#163 162 Evolução read me
  CONTRIBUTING.md
  README.md
Labels: EPS, MDS, Product
