Repository fga-eps-mds/2019.1-ADA, pull requests merged in 2019-06, with the labels that each got.

#240 #218 Add method to set github webhook
  ada/actions/set_repository_github.py
Labels: DevOps, EPS

#241 #209 Refatoração repositório Ada Gitlab
  ada/actions/get_report.py
  ada/actions/set_repository_gitlab.py
Labels: EPS, MDS, Melhoria, Refatoração

#252 #242 Resultados Sprint 10
  _sidebar.md
  docs/assets/img/sprints/sprint10/burndown_de_riscos_sprint10.png
  docs/assets/img/sprints/sprint10/burndown_sprint10.png
  docs/assets/img/sprints/sprint10/cobertura_de_testes_github_sprint10.png
  docs/assets/img/sprints/sprint10/cobertura_de_testes_gitlab_sprint10.png
  docs/assets/img/sprints/sprint10/codeclimate_ada_sprint10.png
  docs/assets/img/sprints/sprint10/codeclimate_github_sprint10.png
  docs/assets/img/sprints/sprint10/codeclimate_gitlab_sprint10.png
  docs/assets/img/sprints/sprint10/quadro_de_conhecimentos_sprint10.png
  docs/assets/img/sprints/sprint10/velocity_sprint10.png
  docs/sprints/sprint10/resultados_sprint10.md
  docs/sprints/sprint9/resultados_sprint9.md
Labels: Documentação, Scrum Master

#257 #211 Refatorar Ada GitHub
  ada/actions/find_project_collaborators.py
  ada/actions/set_repository_github.py
  ada/data/intents/actions.md
  ada/data/intents/random.md
  ada/data/stories/stories.md
  ada/domain.yml
Labels: MDS, Melhoria, Product, Refatoração, enhancement

#258 #253 Planejamento Sprint 11
  _sidebar.md
  docs/sprints/sprint10/resultados_sprint10.md
  docs/sprints/sprint11/planejamento_sprint11.md
Labels: Documentação, Scrum Master

#259 #255 - Atualizar readme
  README.md
  ada/actions/set_repository_gitlab.py
  docker-compose-dev.yml
  env_vars.md
Labels: DevOps, EPS, Melhoria

#264 US17 - Eu, como usuário, desejo que a Ada faça um comentário na issue por mim para entrar em contato com os mantenedores do repositório de maneira mais fácil.
  README.md
  ada/actions/comment_issue.py
  ada/data/intents/actions.md
  ada/data/stories/stories.md
  ada/domain.yml
  env_vars.md
Labels: MDS, Product, enhancement

#250 #US20 issues colaboradores
  ada/actions/action_get_issues_of_contributor.py
  ada/data/intents/actions.md
  ada/data/stories/stories.md
  ada/domain.yml
Labels: MDS

#256 US35 - Eu, como usuário, desejo que a Ada cadastre a minha url do deploy do meu projeto.
  ada/actions/get_url_domain.py
  ada/data/intents/actions.md
  ada/data/stories/stories.md
  ada/domain.yml
Labels: Product

#268 #260 Resultados Sprint 11
  _sidebar.md
  docs/assets/img/sprints/sprint11/burndown_de_riscos_sprint11.png
  docs/assets/img/sprints/sprint11/burndown_sprint11.png
  docs/assets/img/sprints/sprint11/cobertura_de_testes_github_sprint11.png
  docs/assets/img/sprints/sprint11/cobertura_de_testes_gitlab_sprint11.png
  docs/assets/img/sprints/sprint11/codeclimate_ada_sprint11.png
  docs/assets/img/sprints/sprint11/codeclimate_github_sprint11.png
  docs/assets/img/sprints/sprint11/codeclimate_gitlab_sprint11.png
  docs/assets/img/sprints/sprint11/quadro_de_conhecimentos_sprint11.png
  docs/assets/img/sprints/sprint11/velocity_sprint11.png
  docs/sprints/sprint11/resultados_sprint11.md
Labels: Documentação, Scrum Master

#269 #265 Melhoria no fluxo de conversa
  CONTRIBUTING.md
  ada/data/intents/actions.md
  ada/data/intents/general.md
  ada/data/intents/random.md
  ada/data/stories/stories.md
  ada/domain.yml
  ada/instructions.md
  docker-compose.yml
Labels: Melhoria, bug

#280 Change message create issue
  ada/actions/create_issue.py
Labels: Melhoria

#281 #261 Planejamento Sprint 12
  _sidebar.md
  docs/sprints/sprint12/planejamento_sprint12.md
Labels: Documentação, Scrum Master

#223 US24 - Eu, como usuário, desejo que a Ada configure no pipeline de deploy a última versão estável do repositório para recolocar o serviço no ar.
  ada/actions/stable_deploy.py
  ada/data/intents/actions.md
  ada/data/intents/general.md
  ada/data/stories/stories.md
  ada/domain.yml
Labels: MDS, Product, enhancement

#289 #282 Resultados Sprint 12
  _sidebar.md
  docs/assets/img/sprints/sprint12/burndown_de_riscos_sprint12.png
  docs/assets/img/sprints/sprint12/burndown_sprint12.png
  docs/assets/img/sprints/sprint12/cobertura_de_testes_github_sprint12.png
  docs/assets/img/sprints/sprint12/cobertura_de_testes_gitlab_sprint12.png
  docs/assets/img/sprints/sprint12/codeclimate_ada_sprint12.png
  docs/assets/img/sprints/sprint12/codeclimate_github_sprint12.png
  docs/assets/img/sprints/sprint12/codeclimate_gitlab_sprint12.png
  docs/assets/img/sprints/sprint12/quadro_de_conhecimentos_sprint12.png
  docs/assets/img/sprints/sprint12/velocity_sprint12.png
  docs/sprints/sprint12/resultados_sprint12.md
Labels: Documentação, Scrum Master

#287 273 - Aprimorar a ajuda da Ada
  ada/actions/find_project_collaborators.py
  ada/actions/get_report.py
  ada/actions/report_github.py
  ada/actions/rerun_pipeline.py
  ada/actions/set_repository_github.py
  ada/actions/set_repository_gitlab.py
  ada/data/intents/actions.md
  ada/data/intents/general.md
  ada/data/intents/random.md
  ada/domain.yml
Labels: MDS, Melhoria, Product, Product Owner, Teste em Uso

#291 #286 Add explication of how to create issue and issue comment
  ada/data/intents/general.md
  ada/data/stories/stories.md
  ada/domain.yml
Labels: MDS, Melhoria, Product, Product Owner, Teste em Uso

#285 #275 Garantir que o usuário se cadastre antes de fazer pedidos a Ada
  ada/actions/action_get_issues_of_contributor.py
  ada/actions/comment_issue.py
  ada/actions/create_issue.py
  ada/actions/find_project_collaborators.py
  ada/actions/get_report.py
  ada/actions/report_github.py
  ada/actions/rerun_pipeline.py
  ada/actions/set_issue_title.py
  ada/actions/set_pipeline.py
  ada/actions/stable_deploy.py
  ada/actions/start.py
  ada/data/intents/actions.md
  ada/domain.yml
Labels: Melhoria, Product, Product Owner, Teste em Uso, bug, help wanted

#296 HOTFIX Change start message
  ada/actions/start.py
Labels: bug

#299 #295 Atualizar Resultados das Sprints
  docs/sprints/sprint10/resultados_sprint10.md
  docs/sprints/sprint11/resultados_sprint11.md
  docs/sprints/sprint12/planejamento_sprint12.md
  docs/sprints/sprint12/resultados_sprint12.md
  docs/sprints/sprint3/resultados_sprint3.md
  docs/sprints/sprint5/resultados_sprint5.md
  docs/sprints/sprint6/resultados_sprint6.md
  docs/sprints/sprint7/resultados_sprint7.md
  docs/sprints/sprint8/resultados_sprint8.md
  docs/sprints/sprint9/resultados_sprint9.md
Labels: Documentação, Scrum Master

#297 #294 Atualizar a descrição de ferramentas e métricas utilizadas
  _sidebar.md
  docs/project/metrics_and_indicators.md
Labels: Documentação, Scrum Master

#306 #283 Planejamento Sprint 13
  _sidebar.md
  docs/sprints/sprint13/planejamento_sprint13.md
Labels: Documentação, Scrum Master

#309 #303 Resultados Sprint 13
  _sidebar.md
  docs/assets/img/sprints/sprint13/burndown_de_riscos_sprint13.png
  docs/assets/img/sprints/sprint13/burndown_sprint13.png
  docs/assets/img/sprints/sprint13/cobertura_de_testes_github_sprint13.png
  docs/assets/img/sprints/sprint13/cobertura_de_testes_gitlab_sprint13.png
  docs/assets/img/sprints/sprint13/codeclimate_ada_sprint13.png
  docs/assets/img/sprints/sprint13/codeclimate_github_sprint13.png
  docs/assets/img/sprints/sprint13/codeclimate_gitlab_sprint13.png
  docs/assets/img/sprints/sprint13/quadro_de_conhecimentos_sprint13.png
  docs/assets/img/sprints/sprint13/velocity_sprint13.png
  docs/project/postmortem.md
  docs/sprints/sprint13/resultados_sprint13.md
Labels: Documentação, Scrum Master

#311 HOTFIX Rerun Pipeline
  ada/actions/rerun_pipeline.py
Labels: bug

#312 Hotfix Custom Actions
  ada/actions/set_pipeline.py
  ada/actions/stable_deploy.py
  ada/data/intents/actions.md
  ada/data/intents/general.md
  ada/data/stories/stories.md
  ada/domain.yml
Labels: bug, help wanted

#314 Cadastro de repositórios de organizações e alterações nas mensagens, intents e stories
  ada/actions/find_project_collaborators.py
  ada/actions/set_repository_github.py
  ada/data/intents/actions.md
  ada/data/stories/stories.md
Labels: Melhoria, bug

#318 Atualização do Documento de Arquitetura
  docs/assets/img/project/architecture/Arquitetura_final.png
  docs/assets/img/project/architecture/data_modeling/ModelagemdeDados.jpg
  docs/assets/img/project/architecture/data_modeling/ModelagemdeDados.png
  docs/assets/img/project/architecture/data_modeling/ModelagemdeDados2.png
  docs/project/architecture_doc.md
Labels: Arquitetura, Documentação, EPS, Melhoria
