Repository fga-eps-mds/2019.1-ADA, pull requests merged in 2019-03, with the labels that each got.

#5 #1 Add issue template to repository
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: Documentação

#9 #8 Add code of conduct
  CODE_OF_CONDUCT.md
Labels: Documentação

#12 #1 Add acceptance criteria to issue template
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: Documentação

#31 #30 Elaborar Termo de Abertura do Projeto (TAP)
  _sidebar.md
  docs/opening_and_specification/termo_de_abertura_do_projeto.md
Labels: Documentação, EPS

#34 #24 Redigir Entrevista/Reunião com cliente
  _sidebar.md
  docs/requirements_engineering/interview_summary.md
Labels: Documentação, EPS

#35 #27 Create "Plano de Comunicação" document
  _sidebar.md
  docs/project/communication_plan.md
Labels: Documentação, EPS

#37 #18 Create LICENSE
  LICENSE
Labels: EPS, MDS

#36 #16 Add Vision Document
  _sidebar.md
  docs/img/chatops.png
  docs/opening_and_specification/Vision_Document.md
Labels: Documentação, EPS, MDS

#38 #16 hot fix fix path vision document
  _sidebar.md
  docs/opening_and_specification/vision_document.md
Labels: Documentação, MDS

#39 #19 Add Rich Pictures
  _sidebar.md
  docs/img/rich_pictures/caio_picture.png
  docs/img/rich_pictures/erick_picture.png
  docs/img/rich_pictures/guilherme_picture.jpg
  docs/img/rich_pictures/joao_picture.jpg
  docs/img/rich_pictures/lucas_picture.jpg
  docs/opening_and_specification/rich_picture.md
Labels: Documentação, MDS

#44 #40 Criar documentos de Planejamento e Resultados da Sprint 0
  _sidebar.md
  docs/img/rich_pictures/erick_picture.png
  docs/img/sprints/sprint0/burndown_sprint0.png
  docs/img/sprints/sprint0/quadro_de_conhecimentos_sprint0.png
  docs/img/sprints/sprint0/velocity_sprint0.jpg
  docs/opening_and_specification/rich_picture.md
  docs/sprints/planejamento_sprint0.md
  docs/sprints/resultados_sprint0.md
Labels: Documentação, EPS, Scrum Master

#46 #19 fix image insertion method
  docs/img/rich_pictures/caio_picture.png
  docs/img/rich_pictures/guilherme_picture.jpg
  docs/img/rich_pictures/guilherme_picture.png
  docs/img/rich_pictures/joao_picture.jpg
  docs/img/rich_pictures/joao_picture.png
  docs/img/rich_pictures/lucas_picture.jpg
  docs/img/rich_pictures/lucas_picture.png
  docs/opening_and_specification/rich_picture.md
  docs/opening_and_specification/vision_document.md
Labels: Documentação, bug

#45 #41 Criar o Documento de Planejamento da Sprint 1
  _sidebar.md
  docs/sprints/planejamento_sprint1.md
Labels: Documentação, EPS, Scrum Master

#43 #22 Elaborar EAP
  _sidebar.md
  docs/img/eap/eap_v1.jpg
  docs/img/eap/eap_v2.jpg
  docs/opening_and_specification/eap.md
Labels: Documentação, EPS

#42 #20 Elaborar Canvas
  _sidebar.md
  docs/img/canvas/canvas_v0_1.jpeg
  docs/img/canvas/canvas_v1.png
  docs/opening_and_specification/canvas.md
Labels: Documentação, EPS

#47 #23 Elaborar README
  README.md
Labels: Documentação, EPS

#49 #17 Add bot personality
  _sidebar.md
  docs/opening_and_specification/bot_personality.md
Labels: Documentação, MDS

#48 WIP #21 create gitflow
  _sidebar.md
  docs/project/gitflow.md
Labels: EPS

#51 #50 Criar Documentação de Resultados
  _sidebar.md
  docs/img/sprints/sprint1/burndown_sprint1.png
  docs/img/sprints/sprint1/quadro_de_conhecimentos_sprint1.png
  docs/img/sprints/sprint1/tvi_sprint1.png
  docs/img/sprints/sprint1/velocity_sprint1.png
  docs/img/sprints/sprint1/work_capacity_sprint1.png
  docs/sprints/resultados_sprint1.md
Labels: Documentação, EPS, Scrum Master
