Repository fga-eps-mds/2019.1-ADA, pull requests merged in 2019-05, with the labels that each got.

#166 #131 evoluir ghpages
  _coverpage.md
  docs/assets/css/home.css
  docs/assets/img/logo/Ada.png
  docs/assets/img/logo/Ada_logo.png
  docs/assets/img/logo/Ada_logo_horizontal.png
  docs/assets/img/logo/Ada_logo_vertical.png
Labels: Melhoria

#168 #167 Revisão da Documentação
  _sidebar.md
  docs/assets/img/sprints/sprint0/velocity_sprint0.jpg
  docs/assets/img/sprints/sprint0/velocity_sprint0.png
  docs/assets/img/sprints/sprint1/tvi_sprint1.png
  docs/assets/img/sprints/sprint1/velocity_sprint1.png
  docs/assets/img/sprints/sprint1/work_capacity_sprint1.png
  docs/assets/img/sprints/sprint2/tvi_sprint2.png
  docs/assets/img/sprints/sprint2/velocity_sprint2.png
  docs/assets/img/sprints/sprint2/work_capacity_sprint2.png
  docs/assets/img/sprints/sprint3/tvi_sprint3.png
  docs/assets/img/sprints/sprint3/velocity_sprint3.png
  docs/assets/img/sprints/sprint3/work_capacity_sprint3.png
  docs/product/bot_personality.md
  docs/product/canvas.md
  docs/product/questionnaire.md
  docs/product/rich_picture.md
  docs/product/tap.md
  docs/product/vision_document.md
  docs/project/architecture_doc.md
  docs/project/machine_learning_pipeline.md
  docs/project/measuring_plane.md
  docs/project/style_guide.md
  docs/sprints/sprint0/resultados_sprint0.md
  docs/sprints/sprint1/planejamento_sprint1.md
Labels: Documentação, EPS, MDS

#169 Dados de forma natural
  ada/actions/.gitkeep
  ada/actions/action_build_stage.py
  ada/actions/get_pipeline.py
  ada/actions/set_repositorie.py
  ada/actions/set_user.py
  ada/data/intents/actions.md
  ada/domain.yml
  ada/endpoints.yml
  docker-compose-dev.yml
  docker/actions.requirements.txt
Labels: EPS, MDS, Melhoria

#171 114 melhorar arquitetura
  _coverpage.md
  docs/assets/img/logo/Background.jpg
  docs/assets/img/product/canvas/canvas_v1_1.png
  docs/assets/img/project/architecture/Arquitetura_nova.png
  docs/assets/img/project/architecture/data_modeling/ModelagemdeDados.jpg
  docs/assets/img/project/architecture/pack_diagram/Pacote-ada-geral.jpg
  docs/assets/img/project/architecture/pack_diagram/Pacote-ada-github.jpg
  docs/assets/img/project/architecture/pack_diagram/Pacote-ada-gitlab.jpg
  docs/assets/img/project/architecture/pack_diagram/Pacote-ada.jpg
  docs/product/canvas.md
  docs/project/architecture_doc.md
Labels: Arquitetura, Documentação, EPS

#170 Alteração da Pipeline
  .gitlab-ci.yml
  ada/actions/get_pipeline.py
  ada/actions/set_pipeline.py
  ada/data/intents/actions.md
  ada/data/intents/build_stage.md
  ada/data/intents/general.md
  ada/data/stories/build_stage_storie.md
  ada/data/stories/stories.md
  ada/domain.yml
  ada/endpoints.yml
  docker-compose-dev.yml
Labels: MDS, Melhoria

#172 US30 Receber relatorio gitlab
  ada/actions/get_report.py
  ada/actions/set_repositorie.py
  ada/data/intents/actions.md
  ada/data/stories/stories.md
  ada/domain.yml
Labels: MDS, Product

#175 Hotfix-ActionSetPipeline
  ada/actions/set_pipeline.py
Labels: MDS, Product, bug

#186 #180 Resultados Sprint 6
  _sidebar.md
  docs/assets/img/sprints/sprint6/burndown_de_riscos_sprint6.png
  docs/assets/img/sprints/sprint6/burndown_sprint6.png
  docs/assets/img/sprints/sprint6/quadro_de_conhecimentos_sprint6.png
  docs/assets/img/sprints/sprint6/velocity_sprint6.png
  docs/sprints/sprint6/planejamento_sprint6.md
  docs/sprints/sprint6/resultados_sprint6.md
Labels: Documentação, Scrum Master

#188 US12 - Eu, como usuário, desejo saber as informações sobre os serviços que a Ada oferece.
  ada/data/intents/general.md
  ada/data/intents/random.md
  ada/data/stories/stories.md
  ada/domain.yml
Labels: MDS, Product Owner, enhancement

#191 155 Fix Mapear Conversa
  _sidebar.md
  docs/assets/img/product/conversation_mapping/mapeamento_de_conversa.png
  docs/product/conversation_mapping.md
Labels: MDS, Melhoria, Product, enhancement

#202 #195 Melhora no mapeamento de fluxo de conversas
  _sidebar.md
  docs/assets/img/product/conversation_mapping/mapeamento_de_conversa2.png
  docs/product/conversation_mapping.md
Labels: Documentação, Melhoria

#198 #192 Resultados Sprint 7
  _sidebar.md
  docs/assets/img/sprints/sprint7/burndown_de_riscos_sprint7.png
  docs/assets/img/sprints/sprint7/burndown_sprint7.png
  docs/assets/img/sprints/sprint7/quadro_de_conhecimentos_sprint7.png
  docs/assets/img/sprints/sprint7/velocity_sprint7.png
  docs/sprints/sprint6/resultados_sprint6.md
  docs/sprints/sprint7/resultados_sprint7.md
Labels: Documentação, Scrum Master

#204 285 - Evoluir artefatos
  docs/assets/img/project/architecture/Rasa_arquitetura.png
  docs/assets/img/project/architecture/data_modeling/ModelagemdeDados2.png
  docs/project/architecture_doc.md
Labels: Arquitetura, Documentação, Melhoria

#206 US08 - Eu, como usuário, desejo que a Ada reinicie uma build/pipeline do meu projeto no GitLab CI, caso ela tenha falhado. #194
  ada/actions/rerun_pipeline.py
  ada/data/intents/actions.md
  ada/data/stories/stories.md
  ada/domain.yml
Labels: MDS, enhancement

#214 #203 Resultados Sprint 8
  _sidebar.md
  docs/assets/img/sprints/sprint8/burndown_de_riscos_sprint8.png
  docs/assets/img/sprints/sprint8/burndown_sprint8.png
  docs/assets/img/sprints/sprint8/quadro_de_conhecimentos_sprint8.png
  docs/assets/img/sprints/sprint8/velocity_sprint8.png
  docs/sprints/sprint8/resultados_sprint8.md
Labels: Documentação, Scrum Master

#207 US14 - Eu, como usuário, desejo ser notificado quando a Ada demorar a recuperar informações para saber o status da minha requisição
  ada/actions/get_report.py
  ada/actions/rerun_pipeline.py
  ada/actions/set_pipeline.py
  ada/actions/set_repositorie.py
Labels: MDS, Product

#197 #156 Us16 criar issue
  .gitignore
  ada/actions/create_issue.py
  ada/actions/set_issue_title.py
  ada/actions/set_repository_github.py
  ada/actions/set_repository_gitlab.py
  ada/actions/set_user.py
  ada/actions/start.py
  ada/data/intents/actions.md
  ada/data/intents/general.md
  ada/data/intents/random.md
  ada/data/stories/stories.md
  ada/domain.yml
  docker-compose-dev.yml
Labels: Ambientação, Arquitetura, MDS

#219 #205 Planejamento Sprint 9
  _sidebar.md
  docs/sprints/sprint9/planejamento_sprint9.md
Labels: Documentação, Scrum Master

#217 Envio do código para a branch master
  .gitignore
  ada/actions/create_issue.py
  ada/actions/get_report.py
  ada/actions/rerun_pipeline.py
  ada/actions/set_issue_title.py
  ada/actions/set_pipeline.py
  ada/actions/set_repository_github.py
  ada/actions/set_repository_gitlab.py
  ada/actions/set_user.py
  ada/actions/start.py
  ada/data/intents/actions.md
  ada/data/intents/general.md
  ada/data/intents/random.md
  ada/data/stories/stories.md
  ada/domain.yml
  docker-compose-dev.yml
Labels: EPS

#224 US28 Relatório GitHub
  ada/actions/report_github.py
  ada/data/intents/actions.md
  ada/data/stories/stories.md
  ada/domain.yml
Labels: MDS, Product, enhancement

#233 #225 Resultados Sprint 9
  _sidebar.md
  docs/assets/img/sprints/sprint9/burndown_de_riscos_sprint9.png
  docs/assets/img/sprints/sprint9/burndown_sprint9.png
  docs/assets/img/sprints/sprint9/cobertura_de_testes_github.png
  docs/assets/img/sprints/sprint9/cobertura_de_testes_gitlab.png
  docs/assets/img/sprints/sprint9/quadro_de_conhecimentos_sprint9.png
  docs/assets/img/sprints/sprint9/velocity_sprint9.png
  docs/sprints/sprint9/resultados_sprint9.md
Labels: Documentação, Scrum Master

#238 Merge pull request #224 from fga-eps-mds/US28-RelatorioGitHub
  ada/actions/start.py
  docker-compose-dev.yml
Labels: bug
